[profile.default]
src = "src"
out = "out"
libs = ["lib"]
rpc_endpoints = { mainnet = "${ETH_RPC_URL}" }
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/contracts/",
    "@uniswapContracts/=lib/v3-core/contracts/",
    "@uniswapPeriphery/=lib/v3-periphery/contracts/",
    "forge-std/=lib/forge-std/src/",
]
